### ISSUE TITLE
Incomplete trace on ThunderX2 (R181-T90)

### ISSUE THREAD

**Issue by HighW4y2H3ll** [RICSecLab/coresight-trace#7]
Hi, I was trying to run your trace dump on our box with ThunderX2 CN99xx. However, the traces were jumpy, and a lot of address in the middle weren't logged in the trace dump. Following is the command I ran:
`./cs-trace --verbose=2  -- /bin/ls`
`./coresight-decoder/processor ./coresight-trace/cstrace.bin 0x10 1 /bin/ls 0xaaaae5820000 0xaaaae5840000`

And here's the trace:
[out.log](https://github.com/RICSecLab/coresight-trace/files/7989542/out.log)
 
I can confirm that the addresses are legit in the `ls` program I ran the trace against, but there're a lot more traces missing. Any idea where I should look into? Thanks!

**Comment by retrage** [comment]
Can you check if the `CONTEXTIDR` register is set to the current PID by the OS?

I can see a lot of `ETM4_PKT_I_TRACE_ON` and `ETM4_PKT_I_CTXT` sequences in your trace log. It means the execution goes out of the trace filter range many times. The `cs-trace` uses a Context ID filter and memory range filter to trace only the specified process. The Context ID filter relies on the value of the `CONTEXTIDR` register, which the OS is expected to set the current PID. The `CONFIG_PID_IN_CONTEXTIDR` option enables this behavior. I forgot to add a note about this requirement.

**Comment by HighW4y2H3ll** [comment]
yes, I did have `CONFIG_PID_IN_CONTEXTIDR` set. umm.. how should I check the `CONTEXTIDR` register... I don't have JTAG, but I can probably try kprobe a few syscalls and dump the register and the smp processor id. btw. should I take the specific core offline before I ran traces on it? Or, not initializing coresight tracing for the other cores?

**Comment by HighW4y2H3ll** [comment]
hmmm, okay, I kprobe at `getdents64` (since I'm testing `/bin/ls`). There were 2 `getdents64` called during the `ls`. I got consistent context id and cpu id both of the time -- `contextidr` is the pid of `ls` running on cpu 0. Not feeling very likely... but let me also check whether some part of the code got switched to other cores...

**Comment by HighW4y2H3ll** [comment]
oh... I know what's going on... sorry that I forgot to upload the binary.
[ls.zip](https://github.com/RICSecLab/coresight-trace/files/8010850/ls_tx2.zip)

All those `TRACE_ON`s were from the `bl` instructions.
